### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-sql-basics-app#25]
This started code DOES NOT run!

Can you reload it so I can re download it and do it?

Screen shot below!
<img width="1440" alt="Screen Shot 2022-02-17 at 1 33 54 PM" src="https://user-images.githubusercontent.com/91148652/154557171-cc8438ff-3499-472d-bca6-3845e42bb877.png">

**Comment by rock-chock** [comment]
Hi @jh115424, I had exactly the same issue.

I've started reading all the open issues and found a working solution suggested by @deckikwok. The fix is to simply update the version of Room library in Gradle app file to '2.4.1'. After syncing Gradle, the app successfully runs.
 
https://github.com/google-developer-training/android-basics-kotlin-sql-basics-app/issues/20#issuecomment-1014016806

**Comment by jh115424** [comment]
thanks!

I sent in an issue on the Lunchbox app on the issues list.

It is the 1st one, so you should see it.

thanks,




Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:75b34584-19ed-4a0d-bb7c-64a4a4cb5566]<https://your.tradeinvalet.com/tdhe0j>

________________________________
